In [1]:
import pandas as pd
#pd.set_option("display.max_rows", None)
#pd.set_option("display.max_columns", None)
#pd.set_option("display.large_repr", "truncate")

In [2]:
#Data Inspection
original_data = pd.read_csv("../raw_data/crime_data_2010_2019.csv")
original_data.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,2010 Feb 20 12:00:00 AM,2010 Feb 20 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,2010 Sep 13 12:00:00 AM,2010 Sep 12 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,2010 Aug 09 12:00:00 AM,2010 Aug 09 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,2010 Jan 05 12:00:00 AM,2010 Jan 05 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,2010 Jan 03 12:00:00 AM,2010 Jan 02 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488

In [3]:
original_data.shape

(2133137, 28)

In [4]:
original_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2133137 entries, 0 to 2133136
Data columns (total 28 columns):
 #   Column          Dtype
---  ------          -----
 0   DR_NO           int64
 1   Date Rptd       str
 2   DATE OCC        str
 3   TIME OCC        int64
 4   AREA            int64
 5   AREA NAME       str
 6   Rpt Dist No     int64
 7   Part 1-2        int64
 8   Crm Cd          int64
 9   Crm Cd Desc     str
 10  Mocodes         str
 11  Vict Age        int64
 12  Vict Sex        str
 13  Vict Descent    str
 14  Premis Cd       float64
 15  Premis Desc     str
 16  Weapon Used Cd  float64
 17  Weapon Desc     str
 18  Status          str
 19  Status Desc     str
 20  Crm Cd 1        float64
 21  Crm Cd 2        float64
 22  Crm Cd 3        float64
 23  Crm Cd 4        float64
 24  LOCATION        str
 25  Cross Street    str
 26  LAT             float64
 27  LON             float64
dtypes: float64(8), int64(7), str(13)
memory usage: 455.7 MB

In [5]:
data = original_data.copy()

In [6]:
# Columns to drop - they are not important
cols_to_drop = [
    "AREA ",        
    "Rpt Dist No",
    "Part 1-2",
    "Crm Cd",
    "Mocodes",
    "Premis Cd",
    "Weapon Used Cd",
    "Status",
    "Status Desc",
    "Crm Cd 1",
    "Crm Cd 2",
    "Crm Cd 3",
    "Crm Cd 4",
    "LOCATION",
    "Cross Street",
]

# Drop columns
data = data.drop(columns=[col for col in cols_to_drop if col in data.columns])

# Check the result
data.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA NAME',
       'Crm Cd Desc', 'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Desc',
       'Weapon Desc', 'LAT', 'LON'],
      dtype='str')

In [7]:
# Rename columns
data = data.rename(columns={"DR_NO": "ID"})
data = data.rename(columns={"Date Rptd": "DATE RPTD"})
data = data.rename(columns={"AREA NAME": "AREA"})
data = data.rename(columns={"Crm Cd Desc": "CRIME"})
data = data.rename(columns={"Vict Age": "VICT AGE"})
data = data.rename(columns={"Vict Sex": "VICT SEX"})
data = data.rename(columns={"Vict Descent": "VICT DESCENT"})
data = data.rename(columns={"Premis Desc": "PLACE"})
data = data.rename(columns={"Weapon Desc": "WEAPON"})
data.columns

Index(['ID', 'DATE RPTD', 'DATE OCC', 'TIME OCC', 'AREA', 'CRIME', 'VICT AGE',
       'VICT SEX', 'VICT DESCENT', 'PLACE', 'WEAPON', 'LAT', 'LON'],
      dtype='str')

In [8]:
# Convert strings to datetime
data["DATE RPTD"] = pd.to_datetime(data["DATE RPTD"],format="%Y %b %d %I:%M:%S %p")
data["DATE OCC"] = pd.to_datetime(data["DATE OCC"], format="%Y %b %d %I:%M:%S %p")
# Format as dd-mm-yyyy
data["DATE RPTD"] = data["DATE RPTD"].dt.strftime("%Y-%m-%d")
data["DATE OCC"] = data["DATE OCC"].dt.strftime("%Y-%m-%d")

data.head()

,ID,DATE RPTD,DATE OCC,TIME OCC,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,WEAPON,LAT,LON
0,1307355,2010-02-20,2010-02-20,1350,Newton,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,NaN,33.9825,-118.2695
1,11401303,2010-09-13,2010-09-12,45,Pacific,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0,M,W,STREET,NaN,33.9599,-118.3962
2,70309629,2010-08-09,2010-08-09,1515,Newton,OTHER MISCELLANEOUS CRIME,0,M,H,ALLEY,NaN,34.0224,-118.2524
3,90631215,2010-01-05,2010-01-05,150,Hollywood,VIOLATION OF COURT ORDER,47,F,W,STREET,HAND GUN,34.1016,-118.3295
4,100100501,2010-01-03,2010-01-02,2100,Central,"RAPE, ATTEMPTED",47,F,H,ALLEY,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",34.0387,-118.2488

In [9]:
# Ensure time is string and pad with zeros if needed
data['TIME OCC'] = data['TIME OCC'].astype(str).str.zfill(4)
# Convert to proper HH:MM format
data['TIME OCC'] = data['TIME OCC'].str[:2] + ':' + data['TIME OCC'].str[2:]

data.head()

,ID,DATE RPTD,DATE OCC,TIME OCC,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,WEAPON,LAT,LON
0,1307355,2010-02-20,2010-02-20,13:50,Newton,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,NaN,33.9825,-118.2695
1,11401303,2010-09-13,2010-09-12,00:45,Pacific,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0,M,W,STREET,NaN,33.9599,-118.3962
2,70309629,2010-08-09,2010-08-09,15:15,Newton,OTHER MISCELLANEOUS CRIME,0,M,H,ALLEY,NaN,34.0224,-118.2524
3,90631215,2010-01-05,2010-01-05,01:50,Hollywood,VIOLATION OF COURT ORDER,47,F,W,STREET,HAND GUN,34.1016,-118.3295
4,100100501,2010-01-03,2010-01-02,21:00,Central,"RAPE, ATTEMPTED",47,F,H,ALLEY,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",34.0387,-118.2488

In [10]:
# Combine DATE OCC and TIME OCC into a single datetime column
# This allows merging with weather data on an hourly basis
data.loc[:, "DATETIME OCC"] = pd.to_datetime(
    data["DATE OCC"] + " " + data["TIME OCC"],
    format="%Y-%m-%d %H:%M"
)

# Round DATETIME OCC to nearest full hour
data.loc[:, "DATETIME OCC"] = data["DATETIME OCC"].dt.floor("h")

# Drop DATE OCC and TIME OCC columns
data.drop(columns=["DATE OCC"], inplace=True)
data.drop(columns=["TIME OCC"], inplace=True)

data.head()

,ID,DATE RPTD,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,WEAPON,LAT,LON,DATETIME OCC
0,1307355,2010-02-20,Newton,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,NaN,33.9825,-118.2695,2010-02-20 13:00:00
1,11401303,2010-09-13,Pacific,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0,M,W,STREET,NaN,33.9599,-118.3962,2010-09-12 00:00:00
2,70309629,2010-08-09,Newton,OTHER MISCELLANEOUS CRIME,0,M,H,ALLEY,NaN,34.0224,-118.2524,2010-08-09 15:00:00
3,90631215,2010-01-05,Hollywood,VIOLATION OF COURT ORDER,47,F,W,STREET,HAND GUN,34.1016,-118.3295,2010-01-05 01:00:00
4,100100501,2010-01-03,Central,"RAPE, ATTEMPTED",47,F,H,ALLEY,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",34.0387,-118.2488,2010-01-02 21:00:00

In [11]:
data.isnull().sum()

ID                    0
DATE RPTD             0
AREA                  0
CRIME                 0
VICT AGE              0
VICT SEX         198036
VICT DESCENT     198083
PLACE               188
WEAPON          1416450
LAT                   0
LON                   0
DATETIME OCC          0
dtype: int64

In [12]:
print(data['AREA'].unique())

<StringArray>
[     'Newton',     'Pacific',   'Hollywood',     'Central',   'Northeast',
  'Hollenbeck',    'Foothill',   'Southwest',     'Rampart',   'Southeast',
     'Olympic',    'Wilshire', '77th Street',      'Harbor', 'West Valley',
    'Van Nuys',  'Devonshire',     'Mission',     'West LA',     'Topanga',
 'N Hollywood']
Length: 21, dtype: str

In [13]:
# Rename areas to those used in weather dataset for easier merge
area_mapping = {
    "Newton": "NEWTON",
    "Pacific": "PACIFIC",
    "Hollywood": "HOLLYWOOD",
    "Central": "CENTRAL",
    "Northeast": "NORTHEAST",
    "Hollenbeck": "HOLLENBECK",
    "Foothill": "FOOTHILL",
    "Southwest": "SOUTHWEST",
    "Rampart": "RAMPART",
    "Southeast": "SOUTHEAST",
    "Olympic": "OLYMPIC",
    "Wilshire": "WILSHIRE",
    "77th Street": "77TH STREET",
    "Harbor": "HARBOR",
    "West Valley": "WEST VALLEY",
    "Van Nuys": "VAN NUYS",
    "Devonshire": "DEVONSHIRE",
    "Mission": "MISSION",
    "West LA": "WEST LOS ANGELES",
    "Topanga": "TOPANGA",
    "N Hollywood": "NORTH HOLLYWOOD"
}
data["AREA"] = data["AREA"].map(area_mapping)
print(data['AREA'].unique())

<StringArray>
[          'NEWTON',          'PACIFIC',        'HOLLYWOOD',
          'CENTRAL',        'NORTHEAST',       'HOLLENBECK',
         'FOOTHILL',        'SOUTHWEST',          'RAMPART',
        'SOUTHEAST',          'OLYMPIC',         'WILSHIRE',
      '77TH STREET',           'HARBOR',      'WEST VALLEY',
         'VAN NUYS',       'DEVONSHIRE',          'MISSION',
 'WEST LOS ANGELES',          'TOPANGA',  'NORTH HOLLYWOOD']
Length: 21, dtype: str

In [14]:
print(data['VICT AGE'].unique())

[ 48   0  47  23  46  51  30  55  38  40  24  29  41  11  50  18  37  28
  25  31  36  61  27  32  45  22  35  44  20  33  26  52  62  39  54  76
  16  21  57  34  65   5  49  58  56  59  42   9  60  92  43  19  15  17
  63  83   6 -12  13  12   7  53  10  99  74  84  68  82  66  64  -8  14
  69  70  71  73  78  67  81  72  86  79  75  77   2   4   8  80  93  85
   3  91  89  87  90  88  96  95  97  98  94 -13  -3  -1  -6  -5  -2  -9
  -4 -10 -11  -7 114 118]

In [15]:
# Replace invalid ages with Unknown
data["VICT AGE"] = data["VICT AGE"].apply(lambda x: x if 0 < x <= 100 else 'Unknown')
print(data["VICT AGE"].unique())

[48 'Unknown' 47 23 46 51 30 55 38 40 24 29 41 11 50 18 37 28 25 31 36 61
 27 32 45 22 35 44 20 33 26 52 62 39 54 76 16 21 57 34 65 5 49 58 56 59 42
 9 60 92 43 19 15 17 63 83 6 13 12 7 53 10 99 74 84 68 82 66 64 14 69 70
 71 73 78 67 81 72 86 79 75 77 2 4 8 80 93 85 3 91 89 87 90 88 96 95 97 98
 94]

In [16]:
print(data['VICT SEX'].unique())

<StringArray>
['M', 'F', nan, 'X', 'H', '-', 'N']
Length: 7, dtype: str

In [17]:
# Replace invalid sex values with X
data["VICT SEX"] = data["VICT SEX"].apply(
    lambda x: x if x in ["M", "F"] else "X"
)
print(data['VICT SEX'].unique())

<StringArray>
['M', 'F', 'X']
Length: 3, dtype: str

In [18]:
print(data["VICT DESCENT"].unique())

<StringArray>
['H', 'W', 'B', 'A', 'O', 'X', 'K', nan, 'I', 'J', 'F', 'C', 'P', 'V', 'U',
 'G', 'D', 'S', 'Z', 'L', '-']
Length: 21, dtype: str

In [19]:
valid_descent = ['A','B','C','D','F','G','H','I','J','K','L','O','P','S','U','V','W','X','Z']
# Replace invalid descent values with X
data["VICT DESCENT"] = data["VICT DESCENT"].apply(lambda x: x if x in valid_descent else "X")
print(data["VICT DESCENT"].unique())

<StringArray>
['H', 'W', 'B', 'A', 'O', 'X', 'K', 'I', 'J', 'F', 'C', 'P', 'V', 'U', 'G',
 'D', 'S', 'Z', 'L']
Length: 19, dtype: str

In [20]:
place_counts = data["PLACE"].value_counts(dropna=False)
print(f"Number of rows: {place_counts.shape[0]}")
place_counts.to_frame()

Number of rows: 320

                                               count
PLACE
STREET                                        475400
SINGLE FAMILY DWELLING                        434577
MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)  267997
PARKING LOT                                   151357
SIDEWALK                                      105962
...                                              ...
MTA - SILVER LINE - LAC/USC MEDICAL CENTER         2
REDLINE SUBWAY TUNNEL                              1
GREEN LINE (I-105 FWY LEVEL TRAIN)                 1
TACTICAL SIGNIFICANCE                              1
DEPT OF DEFENSE FACILITY                           1

[320 rows x 1 columns]

In [21]:
# Fill NaN with "UNKNOWN"
data["PLACE"] = data["PLACE"].fillna("UNKNOWN")

# Replace retired duplicate entries with "UNKNOWN"
data["PLACE"] = data["PLACE"].replace("RETIRED (DUPLICATE) DO NOT USE THIS CODE", "UNKNOWN")

# Mask for only rows where PLACE starts with "MTA -"
metro_mask = data["PLACE"].str.startswith("MTA -")
data.loc[metro_mask, "PLACE"] = "MTA"

place_counts = data["PLACE"].value_counts(dropna=False)
print(f"Number of rows: {place_counts.shape[0]}")
place_counts.to_frame()

Number of rows: 232

                                               count
PLACE
STREET                                        475400
SINGLE FAMILY DWELLING                        434577
MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)  267997
PARKING LOT                                   151357
SIDEWALK                                      105962
...                                              ...
HARBOR FRWY STATION (NOT LINE SPECIFIC)            2
REDLINE SUBWAY TUNNEL                              1
GREEN LINE (I-105 FWY LEVEL TRAIN)                 1
TACTICAL SIGNIFICANCE                              1
DEPT OF DEFENSE FACILITY                           1

[232 rows x 1 columns]

In [22]:
weapon_counts = data["WEAPON"].value_counts(dropna=False)
print(f"Number of rows: {weapon_counts.shape[0]}")
weapon_counts.to_frame()

Number of rows: 80

                                                  count
WEAPON
NaN                                             1416450
STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)   434834
VERBAL THREAT                                     58930
UNKNOWN WEAPON/OTHER WEAPON                       58121
HAND GUN                                          34240
...                                                 ...
MAC-10 SEMIAUTOMATIC ASSAULT WEAPON                  11
ANTIQUE FIREARM                                      10
MAC-11 SEMIAUTOMATIC ASSAULT WEAPON                   7
M1-1 SEMIAUTOMATIC ASSAULT RIFLE                      3
M-14 SEMIAUTOMATIC ASSAULT RIFLE                      1

[80 rows x 1 columns]

In [23]:
# Fill NaN with "No Weapon"
data["WEAPON"] = data["WEAPON"].fillna("No Weapon")

# Define 10 categories (9 + 'Other')
weapon_mapping = {
    # Firearms
    "HAND GUN": "Firearm",
    "SEMI-AUTOMATIC PISTOL": "Firearm",
    "REVOLVER": "Firearm",
    "AIR PISTOL/REVOLVER/RIFLE/BB GUN": "Firearm",
    "RIFLE": "Firearm",
    "SHOTGUN": "Firearm",
    "AUTOMATIC WEAPON/SUB-MACHINE GUN": "Firearm",
    "ASSAULT WEAPON/UZI/AK47/ETC": "Firearm",
    "UZI SEMIAUTOMATIC ASSAULT RIFLE": "Firearm",
    "MAC-10 SEMIAUTOMATIC ASSAULT WEAPON": "Firearm",
    "MAC-11 SEMIAUTOMATIC ASSAULT WEAPON": "Firearm",
    "SEMI-AUTOMATIC RIFLE": "Firearm",
    "UNK TYPE SEMIAUTOMATIC ASSAULT RIFLE": "Firearm",
    "M-14 SEMIAUTOMATIC ASSAULT RIFLE": "Firearm",
    "M1-1 SEMIAUTOMATIC ASSAULT RIFLE": "Firearm",
    "RELIC FIREARM": "Firearm",
    "OTHER FIREARM": "Firearm",
    "UNKNOWN FIREARM": "Firearm",
    "SIMULATED GUN": "Firearm",
    "HECKLER & KOCH 93 SEMIAUTOMATIC ASSAULT RIFLE": "Firearm",
    "SAWED OFF RIFLE/SHOTGUN": "Firearm",
    "HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE": "Firearm",
    "STARTER PISTOL/REVOLVER": "Firearm",
    "ANTIQUE FIREARM": "Firearm",

    # Knives / Sharp objects
    "KNIFE WITH BLADE 6INCHES OR LESS": "Knife/Sharp Object",
    "OTHER KNIFE": "Knife/Sharp Object",
    "FOLDING KNIFE": "Knife/Sharp Object",
    "KNIFE WITH BLADE OVER 6 INCHES IN LENGTH": "Knife/Sharp Object",
    "KITCHEN KNIFE": "Knife/Sharp Object",
    "DIRK/DAGGER": "Knife/Sharp Object",
    "BOWIE KNIFE": "Knife/Sharp Object",
    "CLEAVER": "Knife/Sharp Object",
    "STRAIGHT RAZOR": "Knife/Sharp Object",
    "RAZOR": "Knife/Sharp Object",
    "RAZOR BLADE": "Knife/Sharp Object",
    "UNKNOWN TYPE CUTTING INSTRUMENT": "Knife/Sharp Object",
    "OTHER CUTTING INSTRUMENT": "Knife/Sharp Object",
    "SWITCH BLADE": "Knife/Sharp Object",
    "AXE": "Knife/Sharp Object",
    "SCISSORS": "Knife/Sharp Object",
    "ICE PICK": "Knife/Sharp Object",
    "MACHETE": "Knife/Sharp Object",
    "SWORD": "Knife/Sharp Object",
    "SCREWDRIVER": "Knife/Sharp Object",
    "GLASS": "Knife/Sharp Object",
    
    # Strong-Arm (personal bodily force)
    "STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)": "Strong-Arm",

    # Blunt objects
    "STICK": "Blunt Object",
    "CLUB/BAT": "Blunt Object",
    "BLUNT INSTRUMENT": "Blunt Object",
    "PIPE/METAL PIPE": "Blunt Object",
    "TIRE IRON": "Blunt Object",
    "HAMMER": "Blunt Object",
    "BOARD": "Blunt Object",
    "BELT FLAILING INSTRUMENT/CHAIN": "Blunt Object",
    "BLACKJACK": "Blunt Object",
    "FIXED OBJECT": "Blunt Object",
    "BOTTLE": "Blunt Object",
    "BRASS KNUCKLES": "Blunt Object",
    "ROCK/THROWN OBJECT": "Blunt Object",
    "CONCRETE BLOCK/BRICK": "Blunt Object",

    # Chemical
    "MACE/PEPPER SPRAY": "Chemical",
    "CAUSTIC CHEMICAL/POISON": "Chemical",
    "SCALDING LIQUID": "Chemical",
    "LIQUOR/DRUGS": "Chemical",

    # Explosive/Fire
    "EXPLOXIVE DEVICE": "Explosive/Fire",
    "BOMB THREAT": "Explosive/Fire",
    "FIRE": "Explosive/Fire",

    # Vehicle
    "VEHICLE": "Vehicle",

    # Threats
    "VERBAL THREAT": "Threat",
    "PHYSICAL PRESENCE": "Threat",
    "DEMAND NOTE": "Threat",

    # No Weapon
    "No Weapon": "No Weapon"
}
# Apply mapping
data["WEAPON CATEGORY"] = data["WEAPON"].map(weapon_mapping).fillna("Other")

# Drop original WEAPON column
data.drop(columns=["WEAPON"], inplace=True)

# Check result
weapon_counts = data["WEAPON CATEGORY"].value_counts(dropna=False)
print(f"Number of rows: {weapon_counts.shape[0]}")
weapon_counts.to_frame()

Number of rows: 10

                      count
WEAPON CATEGORY
No Weapon           1416450
Strong-Arm           434834
Firearm               71032
Threat                60995
Other                 59307
Knife/Sharp Object    44461
Blunt Object          32535
Vehicle                7291
Chemical               5008
Explosive/Fire         1224

In [24]:
# Define approximate geographic bounding box for Los Angeles area
lat_min2, lat_max2 = 33.6, 34.4
lon_min2, lon_max2 = -118.8, -118.1

# A stricter bounding box could be used as shown below
#lat_min1, lat_max1 = 33.7, 34.35
#lon_min1, lon_max1 = -118.7, -118.15

# Filter incidents located OUTSIDE the Los Angeles boundary
outside = data[
    (data["LAT"] < lat_min2) |
    (data["LAT"] > lat_max2) |
    (data["LON"] < lon_min2) |
    (data["LON"] > lon_max2)
]

print("Outside LA:", len(outside))

Outside LA: 1033

In [25]:
data.shape

(2133137, 12)

In [26]:
# Keep only rows inside LA bounding box
data = data[
    (data["LAT"].between(33.6, 34.4)) &
    (data["LON"].between(-118.8, -118.1))
]

data.shape

(2132104, 12)

In [27]:
data.isnull().sum()

ID                 0
DATE RPTD          0
AREA               0
CRIME              0
VICT AGE           0
VICT SEX           0
VICT DESCENT       0
PLACE              0
LAT                0
LON                0
DATETIME OCC       0
WEAPON CATEGORY    0
dtype: int64

In [28]:
data.head()

,ID,DATE RPTD,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY
0,1307355,2010-02-20,NEWTON,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon
1,11401303,2010-09-13,PACIFIC,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon
2,70309629,2010-08-09,NEWTON,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon
3,90631215,2010-01-05,HOLLYWOOD,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm
4,100100501,2010-01-03,CENTRAL,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm

In [35]:
# Crime check
crime_counts = data["CRIME"].value_counts(dropna=False)
print(f"Number of rows: {crime_counts.shape[0]}")
crime_counts.to_frame()
crime_counts.to_frame(name="count").to_csv("../processed_data/crime_categories.csv")

Number of rows: 142

In [31]:
# Export the processed DataFrame to CSV
data.to_csv("../processed_data/cleaned_crime_data.csv", index=False)

In [36]:
def categorize_crime(crime):
    c = crime.upper()

    # 1. Violent
    if any(x in c for x in ['ASSAULT', 'ROBBERY', 'HOMICIDE', 'KIDNAPPING', 'THREAT']):
        return 'Violent'

    # 2. Sexual
    elif any(x in c for x in ['RAPE', 'SEX', 'SODOMY', 'INDECENT', 'LEWD', 'PORN', 'INCEST', 'BEAST']):
        return 'Sexual'

    # 3. Property
    elif any(x in c for x in ['BURGLARY', 'THEFT', 'SHOPLIFT', 'PICKPOCKET', 'PURSE']):
        return 'Property'

    # 4. Vehicle
    elif any(x in c for x in ['VEHICLE', 'MOTOR', 'BIKE', 'BOAT', 'DWOC']):
        return 'Vehicle'

    # 5. Fraud
    elif any(x in c for x in ['FRAUD', 'FORGERY', 'EMBEZZLEMENT', 'BUNCO', 'COUNTERFEIT']):
        return 'Fraud'

    # 6. Vandalism / Arson
    elif any(x in c for x in ['VANDALISM', 'ARSON']):
        return 'Vandalism'

    # 7. Weapons
    elif any(x in c for x in ['WEAPON', 'FIREARM', 'SHOT']):
        return 'Weapons'

    # 8. Public Order
    elif any(x in c for x in ['TRESPASS', 'DISTURB', 'PROWLER', 'RIOT', 'DISPERSE']):
        return 'Public Order'

    # 9. Family / Domestic
    elif any(x in c for x in ['CHILD', 'INTIMATE', 'DOMESTIC']):
        return 'Domestic'

    # 10. Other
    else:
        return 'Other'

In [38]:
data["crime_category"] = data["CRIME"].apply(categorize_crime)

In [39]:
# Export the processed DataFrame to CSV
data.to_csv("../processed_data/cleaned_crime_data_with_categories.csv", index=False)