In [13]:
import pandas as pd

In [14]:
#Crime data
crime_data = pd.read_csv("../processed_data/cleaned_crime_data.csv")
crime_data.head()

,ID,DATE RPTD,DATE OCC,TIME OCC,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,WEAPON CATEGORY,DATETIME OCC
0,1307355,2010-02-20,2010-02-20,13:50,NEWTON,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,No Weapon,2010-02-20 14:00:00
1,11401303,2010-09-13,2010-09-12,00:45,PACIFIC,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,No Weapon,2010-09-12 01:00:00
2,70309629,2010-08-09,2010-08-09,15:15,NEWTON,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,No Weapon,2010-08-09 15:00:00
3,90631215,2010-01-05,2010-01-05,01:50,HOLLYWOOD,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,Firearm,2010-01-05 02:00:00
4,100100501,2010-01-03,2010-01-02,21:00,CENTRAL,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,Strong-Arm,2010-01-02 21:00:00

In [15]:
#Weather data
weather_data = pd.read_csv("../processed_data/weather_2010_2019_hourly.csv")
weather_data.head()

              datetime  temperature  precipitation  wind_speed    APREC
0  2010-01-01 00:00:00          6.2            0.0         9.3  MISSION
1  2010-01-01 01:00:00          5.8            0.0         9.1  MISSION
2  2010-01-01 02:00:00          5.6            0.0         9.8  MISSION
3  2010-01-01 03:00:00          5.4            0.0        10.2  MISSION
4  2010-01-01 04:00:00          5.4            0.0        10.7  MISSION

In [16]:
# Merge on both datetime and area
merged_data = pd.merge(
    crime_data,
    weather_data,
    left_on=['DATETIME OCC', 'AREA'],
    right_on=['datetime', 'APREC'],
    how='left'  
)

merged_data.head()

,ID,DATE RPTD,DATE OCC,TIME OCC,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,WEAPON CATEGORY,DATETIME OCC,datetime,temperature,precipitation,wind_speed,APREC
0,1307355,2010-02-20,2010-02-20,13:50,NEWTON,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,No Weapon,2010-02-20 14:00:00,2010-02-20 14:00:00,14.6,0.0,9.6,NEWTON
1,11401303,2010-09-13,2010-09-12,00:45,PACIFIC,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,No Weapon,2010-09-12 01:00:00,2010-09-12 01:00:00,16.4,0.0,4.6,PACIFIC
2,70309629,2010-08-09,2010-08-09,15:15,NEWTON,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,No Weapon,2010-08-09 15:00:00,2010-08-09 15:00:00,25.5,0.0,11.5,NEWTON
3,90631215,2010-01-05,2010-01-05,01:50,HOLLYWOOD,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,Firearm,2010-01-05 02:00:00,2010-01-05 02:00:00,7.6,0.0,7.6,HOLLYWOOD
4,100100501,2010-01-03,2010-01-02,21:00,CENTRAL,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,Strong-Arm,2010-01-02 21:00:00,2010-01-02 21:00:00,11.6,0.0,8.5,CENTRAL

In [17]:
# Drop unnecessary columns
merged_data.drop(
    columns=['AREA', 'datetime', 'APREC', 'DATETIME OCC'],
    inplace=True
)

merged_data.head()

,ID,DATE RPTD,DATE OCC,TIME OCC,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,WEAPON CATEGORY,temperature,precipitation,wind_speed
0,1307355,2010-02-20,2010-02-20,13:50,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,No Weapon,14.6,0.0,9.6
1,11401303,2010-09-13,2010-09-12,00:45,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,No Weapon,16.4,0.0,4.6
2,70309629,2010-08-09,2010-08-09,15:15,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,No Weapon,25.5,0.0,11.5
3,90631215,2010-01-05,2010-01-05,01:50,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,Firearm,7.6,0.0,7.6
4,100100501,2010-01-03,2010-01-02,21:00,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,Strong-Arm,11.6,0.0,8.5

In [18]:
merged_data = merged_data.rename(columns={"temperature": "TEMPERATURE"})
merged_data = merged_data.rename(columns={"precipitation": "PERCIPITATION"})
merged_data = merged_data.rename(columns={"wind_speed": "WIND SPEED"})

In [19]:
merged_data.head()

,ID,DATE RPTD,DATE OCC,TIME OCC,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED
0,1307355,2010-02-20,2010-02-20,13:50,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,No Weapon,14.6,0.0,9.6
1,11401303,2010-09-13,2010-09-12,00:45,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,No Weapon,16.4,0.0,4.6
2,70309629,2010-08-09,2010-08-09,15:15,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,No Weapon,25.5,0.0,11.5
3,90631215,2010-01-05,2010-01-05,01:50,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,Firearm,7.6,0.0,7.6
4,100100501,2010-01-03,2010-01-02,21:00,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,Strong-Arm,11.6,0.0,8.5

In [20]:
# Export the processed DataFrame to CSV
merged_data.to_csv("../processed_data/merged_weather_crime_data.csv", index=False)

In [21]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132104 entries, 0 to 2132103
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   ID               int64
 1   DATE RPTD        object
 2   DATE OCC         object
 3   TIME OCC         object
 4   CRIME            object
 5   VICT AGE         object
 6   VICT SEX         object
 7   VICT DESCENT     object
 8   PLACE            object
 9   LAT              float64
 10  LON              float64
 11  WEAPON CATEGORY  object
 12  TEMPERATURE      float64
 13  PERCIPITATION    float64
 14  WIND SPEED       float64
dtypes: float64(5), int64(1), object(9)
memory usage: 244.0+ MB