In [25]:
import pandas as pd

In [31]:
#Crime data
crime_data = pd.read_csv("../processed_data/cleaned_crime_data.csv")
crime_data.head()

,ID,DATE RPTD,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY
0,1307355,2010-02-20,NEWTON,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon
1,11401303,2010-09-13,PACIFIC,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon
2,70309629,2010-08-09,NEWTON,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon
3,90631215,2010-01-05,HOLLYWOOD,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm
4,100100501,2010-01-03,CENTRAL,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm

In [32]:
#Weather data
weather_data = pd.read_csv("../processed_data/weather_2010_2019_hourly.csv")
weather_data.head()

,datetime,temperature,precipitation,wind_speed,rain,snowfall,APREC
0,2010-01-01 00:00:00,6.2,0.0,9.3,0.0,0.0,MISSION
1,2010-01-01 01:00:00,5.8,0.0,9.1,0.0,0.0,MISSION
2,2010-01-01 02:00:00,5.6,0.0,9.8,0.0,0.0,MISSION
3,2010-01-01 03:00:00,5.4,0.0,10.2,0.0,0.0,MISSION
4,2010-01-01 04:00:00,5.4,0.0,10.7,0.0,0.0,MISSION

In [33]:
weather_data.shape

(1840608, 7)

In [34]:
# Merge on both datetime and area
merged_data = pd.merge(
    crime_data,
    weather_data,
    left_on=['DATETIME OCC', 'AREA'],
    right_on=['datetime', 'APREC'],
    how='left'  
)

merged_data.head()

,ID,DATE RPTD,AREA,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,datetime,temperature,precipitation,wind_speed,rain,snowfall,APREC
0,1307355,2010-02-20,NEWTON,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,2010-02-20 13:00:00,14.2,0.0,9.7,0.0,0.0,NEWTON
1,11401303,2010-09-13,PACIFIC,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,2010-09-12 00:00:00,16.5,0.0,4.1,0.0,0.0,PACIFIC
2,70309629,2010-08-09,NEWTON,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,2010-08-09 15:00:00,25.5,0.0,11.5,0.0,0.0,NEWTON
3,90631215,2010-01-05,HOLLYWOOD,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,2010-01-05 01:00:00,8.1,0.0,7.4,0.0,0.0,HOLLYWOOD
4,100100501,2010-01-03,CENTRAL,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,2010-01-02 21:00:00,11.6,0.0,8.5,0.0,0.0,CENTRAL

In [35]:
# Drop unnecessary columns
merged_data.drop(
    columns=['AREA', 'datetime', 'APREC'],
    inplace=True
)

merged_data.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,temperature,precipitation,wind_speed,rain,snowfall
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0

In [36]:
merged_data = merged_data.rename(columns={"temperature": "TEMPERATURE"})
merged_data = merged_data.rename(columns={"precipitation": "PERCIPITATION"})
merged_data = merged_data.rename(columns={"wind_speed": "WIND SPEED"})
merged_data = merged_data.rename(columns={"rain": "RAIN"})
merged_data = merged_data.rename(columns={"snowfall": "SNOWFALL"})

In [37]:
merged_data.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0

In [38]:
# Export the processed DataFrame to CSV
merged_data.to_csv("../processed_data/merged_weather_crime_data.csv", index=False)

In [39]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132104 entries, 0 to 2132103
Data columns (total 16 columns):
 #   Column           Dtype
---  ------           -----
 0   ID               int64
 1   DATE RPTD        object
 2   CRIME            object
 3   VICT AGE         object
 4   VICT SEX         object
 5   VICT DESCENT     object
 6   PLACE            object
 7   LAT              float64
 8   LON              float64
 9   DATETIME OCC     object
 10  WEAPON CATEGORY  object
 11  TEMPERATURE      float64
 12  PERCIPITATION    float64
 13  WIND SPEED       float64
 14  RAIN             float64
 15  SNOWFALL         float64
dtypes: float64(7), int64(1), object(8)
memory usage: 260.3+ MB