In [27]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [28]:
# Define categorical data types to reduce memory usage
dtype_dict = {
    "CRIME": "category",
    "VICT SEX": "category",
    "VICT DESCENT": "category",
    "PLACE": "category",
    "WEAPON CATEGORY": "category",
}

# Load merged weather and crime dataset with optimized memory settings
weather_crime_data = pd.read_csv(
    "../processed_data/merged_weather_crime_data.csv",
    dtype=dtype_dict,
    parse_dates=["DATE RPTD", "DATETIME OCC"],
    low_memory=False
)

weather_crime_data.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0

In [29]:
weather_crime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132104 entries, 0 to 2132103
Data columns (total 16 columns):
 #   Column           Dtype
---  ------           -----
 0   ID               int64
 1   DATE RPTD        datetime64[ns]
 2   CRIME            category
 3   VICT AGE         object
 4   VICT SEX         category
 5   VICT DESCENT     category
 6   PLACE            category
 7   LAT              float64
 8   LON              float64
 9   DATETIME OCC     datetime64[ns]
 10  WEAPON CATEGORY  category
 11  TEMPERATURE      float64
 12  PERCIPITATION    float64
 13  WIND SPEED       float64
 14  RAIN             float64
 15  SNOWFALL         float64
dtypes: category(5), datetime64[ns](2), float64(7), int64(1), object(1)
memory usage: 193.2+ MB

In [30]:
weather_crime = weather_crime_data.copy()
weather_crime.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0

In [31]:
# Create spatial point geometry from longitude and latitude coordinates
weather_crime["GEOMETRY"] = weather_crime.apply(
    lambda row: Point(row["LON"], row["LAT"]),
    axis=1
)

In [32]:
# Convert DataFrame to GeoDataFrame
weather_crime_gdf = gpd.GeoDataFrame(weather_crime, geometry="GEOMETRY", crs="EPSG:4326")

In [33]:
weather_crime_gdf.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,GEOMETRY
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0,POINT (-118.2695 33.9825)
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0,POINT (-118.3962 33.9599)
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0,POINT (-118.2524 34.0224)
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0,POINT (-118.3295 34.1016)
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0,POINT (-118.2488 34.0387)

In [34]:
# Load LA City Council district boundaries from shapefile
districts_path = "../raw_data/LA_City_Council_Districts/LA_City_Council_Districts.shp"
districts = gpd.read_file(districts_path)

In [35]:
print(districts.columns)

Index(['OBJECTID', 'MEMBER', 'DISTRICT', 'DIST_MEMBE', 'ShapeSTAre',
       'ShapeSTLen', 'geometry'],
      dtype='object')

In [36]:
print(districts["DISTRICT"].unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

In [37]:
districts

,OBJECTID,MEMBER,DISTRICT,DIST_MEMBE,ShapeSTAre,ShapeSTLen,geometry
0,1,Gilbert Cedillo,1,1 - Gilbert Cedillo,4.205816e+08,173471.010071,"POLYGON ((6480273.222 1839488.399, 6480211.864..."
1,2,Paul Krekorian,2,2 - Paul Krekorian,6.015529e+08,160435.646088,"POLYGON ((6459694.887 1902991.456, 6460526.739..."
2,3,Bob Blumenfield,3,3 - Bob Blumenfield,9.804998e+08,168141.942616,"POLYGON ((6395647.002 1903090.407, 6395646.918..."
3,4,Nithya Raman,4,4 - Nithya Raman,1.364101e+09,335644.030476,"POLYGON ((6404871.571 1898627.766, 6404866.237..."
4,5,Paul Koretz,5,5 - Paul Koretz,9.179116e+08,279746.900835,"POLYGON ((6443136.993 1863527.133, 6442919.776..."
5,6,Nury Martinez,6,6 - Nury Martinez,7.578158e+08,191033.049480,"POLYGON ((6451238.597 1905812.106, 6452300.399..."
6,7,Monica Rodriguez,7,7 - Monica Rodriguez,1.506646e+09,345039.607881,"POLYGON ((6459694.887 1902991.456, 6459010.58 ..."
7,8,Marqueece Harris-Dawson,8,8 - Marqueece Harris-Dawson,4.471151e+08,202334.955714,"POLYGON ((6470694.238 1836040.563, 6471134.523..."
8,9,Curren D. Price Jr.,9,9 - Curren D. Price Jr.,3.634892e+08,108677.129200,"POLYGON ((6489023.277 1827853.077, 6489008.234..."
9,10,Heather Hutt,10,10 - Heather Hutt,4.128908e+08,145875.626458,"POLYGON ((6474480.262 1847607.973, 6474481.58 ..."
10,11,Mike Bonin,11,11 - Mike Bonin,1.774174e+09,401976.220497,"POLYGON ((6416246.478 1869985.914, 6416246.112..."
11,12,John Lee,12,12 - John Lee,1.609899e+09,255642.654298,"POLYGON ((6418701.112 1907124.586, 6418688.06 ..."
12,13,Mitch O'Farrell,13,13 - Mitch O'Farrell,4.519608e+08,213454.055930,"POLYGON ((6477261.344 1878253.078, 6478289.197..."
13,14,Kevin de León,14,14 - Kevin de León,6.868734e+08,215448.696952,"POLYGON ((6489023.277 1827853.077, 6489023.058..."
14,15,Joe Buscaino,15,15 - Joe Buscaino,8.958287e+08,544349.417156,"POLYGON ((6473186.768 1796562.219, 6474615.679..."

In [38]:
# Reproject district polygons to match crime data coordinate system
districts = districts.to_crs(weather_crime_gdf.crs)

In [39]:
districts

,OBJECTID,MEMBER,DISTRICT,DIST_MEMBE,ShapeSTAre,ShapeSTLen,geometry
0,1,Gilbert Cedillo,1,1 - Gilbert Cedillo,4.205816e+08,173471.010071,"POLYGON ((-118.26869 34.04671, -118.26889 34.0..."
1,2,Paul Krekorian,2,2 - Paul Krekorian,6.015529e+08,160435.646088,"POLYGON ((-118.33732 34.22103, -118.33455 34.2..."
2,3,Bob Blumenfield,3,3 - Bob Blumenfield,9.804998e+08,168141.942616,"POLYGON ((-118.54919 34.22053, -118.54918 34.2..."
3,4,Nithya Raman,4,4 - Nithya Raman,1.364101e+09,335644.030476,"POLYGON ((-118.5186 34.2084, -118.51859 34.204..."
4,5,Paul Koretz,5,5 - Paul Koretz,9.179116e+08,279746.900835,"POLYGON ((-118.39158 34.11243, -118.3923 34.11..."
5,6,Nury Martinez,6,6 - Nury Martinez,7.578158e+08,191033.049480,"POLYGON ((-118.36533 34.2287, -118.3618 34.224..."
6,7,Monica Rodriguez,7,7 - Monica Rodriguez,1.506646e+09,345039.607881,"POLYGON ((-118.33732 34.22103, -118.33958 34.2..."
7,8,Marqueece Harris-Dawson,8,8 - Marqueece Harris-Dawson,4.471151e+08,202334.955714,"POLYGON ((-118.30027 34.03716, -118.29882 34.0..."
8,9,Curren D. Price Jr.,9,9 - Curren D. Price Jr.,3.634892e+08,108677.129200,"POLYGON ((-118.23971 34.0148, -118.23976 34.01..."
9,10,Heather Hutt,10,10 - Heather Hutt,4.128908e+08,145875.626458,"POLYGON ((-118.28789 34.06897, -118.28788 34.0..."
10,11,Mike Bonin,11,11 - Mike Bonin,1.774174e+09,401976.220497,"POLYGON ((-118.48052 34.12985, -118.48052 34.1..."
11,12,John Lee,12,12 - John Lee,1.609899e+09,255642.654298,"POLYGON ((-118.47299 34.23194, -118.47302 34.2..."
12,13,Mitch O'Farrell,13,13 - Mitch O'Farrell,4.519608e+08,213454.055930,"POLYGON ((-118.27898 34.1532, -118.27559 34.15..."
13,14,Kevin de León,14,14 - Kevin de León,6.868734e+08,215448.696952,"POLYGON ((-118.23971 34.0148, -118.23971 34.01..."
14,15,Joe Buscaino,15,15 - Joe Buscaino,8.958287e+08,544349.417156,"POLYGON ((-118.29167 33.9287, -118.28696 33.92..."

In [40]:
# Spatially join crimes with districts, assigning each crime to the district it falls within
merged_weather_crime_districts = gpd.sjoin(
    weather_crime_gdf,
    districts,
    how="left",
    predicate="within"
)

merged_weather_crime_districts.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,...,RAIN,SNOWFALL,GEOMETRY,index_right,OBJECTID,MEMBER,DISTRICT,DIST_MEMBE,ShapeSTAre,ShapeSTLen
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,...,0.0,0.0,POINT (-118.2695 33.9825),8.0,9.0,Curren D. Price Jr.,9.0,9 - Curren D. Price Jr.,3.634892e+08,108677.129200
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,...,0.0,0.0,POINT (-118.3962 33.9599),10.0,11.0,Mike Bonin,11.0,11 - Mike Bonin,1.774174e+09,401976.220497
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,...,0.0,0.0,POINT (-118.2524 34.0224),8.0,9.0,Curren D. Price Jr.,9.0,9 - Curren D. Price Jr.,3.634892e+08,108677.129200
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,...,0.0,0.0,POINT (-118.3295 34.1016),12.0,13.0,Mitch O'Farrell,13.0,13 - Mitch O'Farrell,4.519608e+08,213454.055930
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,...,0.0,0.0,POINT (-118.2488 34.0387),13.0,14.0,Kevin de León,14.0,14 - Kevin de León,6.868734e+08,215448.696952

In [41]:
# Remove unnecessary columns
merged_weather_crime_districts = merged_weather_crime_districts.drop(columns=['GEOMETRY', 'index_right', 'OBJECTID', 'MEMBER', 'DIST_MEMBE', 'ShapeSTAre', 'ShapeSTLen'])

merged_weather_crime_districts.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,DISTRICT
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0,9.0
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0,11.0
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0,9.0
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0,13.0
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0,14.0

In [42]:
# Check for any invalid values in the DISTRICT column
merged_weather_crime_districts['DISTRICT'].unique()

array([ 9., 11., 13., 14.,  1., nan,  7.,  8., 15., 10.,  5., 12.,  2.,
        6.,  3.,  4.])

In [43]:
# Count how many crimes were not assigned to any district
merged_weather_crime_districts["DISTRICT"].isna().sum()

12653

In [44]:
# Remove rows with NaN in DISTRICT since they do not belong to any district
merged_weather_crime_districts = (
    merged_weather_crime_districts
    .dropna(subset=["DISTRICT"])
)

In [45]:
# Convert DISTRICT column to integer type
merged_weather_crime_districts["DISTRICT"] = (
    merged_weather_crime_districts["DISTRICT"].astype(int)
)

In [46]:
merged_weather_crime_districts.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2119451 entries, 0 to 2132103
Data columns (total 17 columns):
 #   Column           Dtype
---  ------           -----
 0   ID               int64
 1   DATE RPTD        datetime64[ns]
 2   CRIME            category
 3   VICT AGE         object
 4   VICT SEX         category
 5   VICT DESCENT     category
 6   PLACE            category
 7   LAT              float64
 8   LON              float64
 9   DATETIME OCC     datetime64[ns]
 10  WEAPON CATEGORY  category
 11  TEMPERATURE      float64
 12  PERCIPITATION    float64
 13  WIND SPEED       float64
 14  RAIN             float64
 15  SNOWFALL         float64
 16  DISTRICT         int32
dtypes: category(5), datetime64[ns](2), float64(7), int32(1), int64(1), object(1)
memory usage: 216.3+ MB

In [47]:
merged_weather_crime_districts.isnull().sum()

ID                 0
DATE RPTD          0
CRIME              0
VICT AGE           0
VICT SEX           0
VICT DESCENT       0
PLACE              0
LAT                0
LON                0
DATETIME OCC       0
WEAPON CATEGORY    0
TEMPERATURE        0
PERCIPITATION      0
WIND SPEED         0
RAIN               0
SNOWFALL           0
DISTRICT           0
dtype: int64

In [48]:
merged_weather_crime_districts.head()

,ID,DATE RPTD,CRIME,VICT AGE,VICT SEX,VICT DESCENT,PLACE,LAT,LON,DATETIME OCC,WEAPON CATEGORY,TEMPERATURE,PERCIPITATION,WIND SPEED,RAIN,SNOWFALL,DISTRICT
0,1307355,2010-02-20,VIOLATION OF COURT ORDER,48,M,H,SINGLE FAMILY DWELLING,33.9825,-118.2695,2010-02-20 13:00:00,No Weapon,14.2,0.0,9.7,0.0,0.0,9
1,11401303,2010-09-13,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",Unknown,M,W,STREET,33.9599,-118.3962,2010-09-12 00:00:00,No Weapon,16.5,0.0,4.1,0.0,0.0,11
2,70309629,2010-08-09,OTHER MISCELLANEOUS CRIME,Unknown,M,H,ALLEY,34.0224,-118.2524,2010-08-09 15:00:00,No Weapon,25.5,0.0,11.5,0.0,0.0,9
3,90631215,2010-01-05,VIOLATION OF COURT ORDER,47,F,W,STREET,34.1016,-118.3295,2010-01-05 01:00:00,Firearm,8.1,0.0,7.4,0.0,0.0,13
4,100100501,2010-01-03,"RAPE, ATTEMPTED",47,F,H,ALLEY,34.0387,-118.2488,2010-01-02 21:00:00,Strong-Arm,11.6,0.0,8.5,0.0,0.0,14

In [49]:
merged_weather_crime_districts.shape

(2119451, 17)

In [50]:
# Export the processed DataFrame to CSV
merged_weather_crime_districts.to_csv("../processed_data/merged_weather_crime_districts_data.csv", index=False)